### ISSUE TITLE
Character map duplicated replacement issues and rule order problem

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#17]
Pattern replacements probably shouldn't be applied more than once. For example,

```
  59) Interscript maps/un-jpn-Hrkt-Latn-hepburn.yaml system test for {"source"=>"とうきょう", "expected"=>"tôkyô"}
      Failure/Error: expect(result).to eq(test["expected"])
      
        expected: "tôkyô"
             got: "tôukyoょu"
      
        (compared using ==)
      # ./spec/interscript_spec.rb:16:in `block (5 levels) in <top (required)>'
```

This is a problem. `とうきょう` is only supposed to match these rules:
```
    "とう": "tô"
    "きょう": "kyô"
```

But the result shows it matching (we should have a debugging method to show which rules are matching):

```
    "とう": "tô"
    "う": "u"
    "きょ": "kyo"
# No rule for "ょ"
    "う": "u"
```

We must remove those replaced tokens after they were swapped, and we must ensure that longer patterns are matched first.

**Comment by ronaldtse** [comment]
Moreover, some characters do not have a direct replacement. For example, `ょ` has no character replacement because it does not exist on its own, it can only depend on other characters.

**Comment by andrew2net** [comment]
@ronaldtse I can't find `maps/un-jpn-Hrkt-Latn-hepburn.yaml` system. Have you pushed it?

**Comment by ronaldtse** [comment]
I haven't pushed it. But the same issue applies to `mext-jpn-Hrkt-Latn-hepburn` as you see in #19 .

**Comment by andrew2net** [comment]
@ronaldtse please try it again using the latest master

**Comment by ronaldtse** [comment]
@andrew2net thanks, but the issues in #19 persist, e.g.

```
  13) Interscript maps/mext-jpn-Hrkt-Latn-kunrei.yaml system test for {"source"=>"ぽっぽっや", "expected"=>"poppoyya"}
      Failure/Error: expect(result).to eq(test["expected"])
      
        expected: "poppoyya"
             got: "poppoっya"
      
        (compared using ==)
      # ./spec/interscript_spec.rb:13:in `block (5 levels) in <top (required)>'

```

**Comment by andrew2net** [comment]
@ronaldtse I fixed #19

**Comment by chaaklau** [comment]
This issue is still around. 

In this simple map below, after applying the first rule, `ABCD` becomes `y`, yielding the output string `yE`, which should have removed the context for the second rule. Currently it returns `Z` instead, showing that both rules have been applied, and the offset is not handled correctly. 

```
tests:
  - source: 'ABCDE'
    expected: "yE"

map:
  rules:
  - pattern: 'ABCD'
    result: "y"
  - pattern: 'DE'
    result: "z"
```
(The commit b9154f5 removes this logic and fixes the Russian map which relies on the problematic part.)

**Comment by ronaldtse** [comment]
@andrew2net do you have time to fix this issue? Thanks!

**Comment by andrew2net** [comment]
Rules aways apply to an original string, not to a previous rule result. It's done for a purpose.
For example, we have a string `её` which means `her` in Russian. When we apply a rule which changes first `е` to `ye` we got `yeё`. Then we should apply the rule "`ё` after `е` should be converted to `ye`", but we already replace the first Russian `е` with Latinised `ye`.

**Comment by chaaklau** [comment]
> Rules aways apply to an original string, not to a previous rule result. It's done for a purpose.

This can be problematic (see my comments above).

> For example, we have a string `её` which means `her` in Russian. When we apply a rule which changes first `е` to `ye` we got `yeё`. Then we should apply the rule "`ё` after `е` should be converted to `ye`", but we already replace the first Russian `е` with Latinised `ye`.

Instead of replacing Cyrillic `е` to Latin `ye`, which will remove the context for subsequent rule, one can instead *insert a Latin `y`* before Cyrillic `е`. Then Cyrillic `ё` will still be following Cyrillic `е`, which allows the Latin `y` insertion rule to click in.

Can you please take a look at b9154f5 and check if looks good to you?

**Comment by andrew2net** [comment]
> Instead of replacing Cyrillic `е` to Latin `ye`, which will remove the context for subsequent rule, one can instead _insert a Latin `y`_ before Cyrillic `е`. Then Cyrillic `ё` will still be following Cyrillic `е`, which allows the Latin `y` insertion rule to click in.

I've tried to do that way, but if there are many rules like in `maps/bgnpcgn-rus-Cyrl-Latn-1947.yaml` it becomes too hard to predict all possible changes in previous rules and patterns in the rules become huge and hard to debug.

> Can you please take a look at [b9154f5](https://github.com/riboseinc/interscript/commit/b9154f5b79b643e7eca1a7bfbfaa2b865ff57dc3) and check if looks good to you?

It is similar to my first implementation. For example, the third rule won't work if previous changes `E` or `e`.

I'll think about what we can do with this issue

**Comment by chaaklau** [comment]
> it becomes too hard to predict all possible changes in previous rules and patterns in the rules become huge and hard to debug.

Some writing system requires complex rule-based replacements, e.g. some maps need rules to swap orders of letters (e.g. Xab -> abX), which is impossible if replacement rules can only operate on the original string.

> It is similar to my first implementation. For example, the third rule won't work if previous changes `E` or `e`.

I think it should work if the previous rule does not change Cyrillic `e` into Latin `e`. 
This implementation passes all test cases.

**Comment by andrew2net** [comment]
LGTM. Post rules handle uppercase letters, right?

**Comment by chaaklau** [comment]
> Post rules handle uppercase letters
The postrules in the Russian map handle uppercase letters.
